hasbi/config/routes.rb
Rails.application.routes.draw do
  resources :tabel_pelanggarans
  resources :tabel_area_spvs
  resources :tabel_kendaraans
  resources :tabel_sopirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

hasbi/app/controllers/tabel_pelanggarans_controller.rb
class TabelPelanggaransController < ApplicationController
  before_action :set_tabel_pelanggaran, only: %i[ show edit update destroy ]

  # GET /tabel_pelanggarans or /tabel_pelanggarans.json
  def index
    @tabel_pelanggarans = TabelPelanggaran.all
  end

  # GET /tabel_pelanggarans/1 or /tabel_pelanggarans/1.json
  def show
  end

  # GET /tabel_pelanggarans/new
  def new
    @tabel_pelanggaran = TabelPelanggaran.new
  end

  # GET /tabel_pelanggarans/1/edit
  def edit
  end

  # POST /tabel_pelanggarans or /tabel_pelanggarans.json
  def create
    @tabel_pelanggaran = TabelPelanggaran.new(tabel_pelanggaran_params)

    respond_to do |format|
      if @tabel_pelanggaran.save
        format.html { redirect_to tabel_pelanggaran_url(@tabel_pelanggaran), notice: "Tabel pelanggaran was successfully created." }
        format.json { render :show, status: :created, location: @tabel_pelanggaran }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tabel_pelanggaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabel_pelanggarans/1 or /tabel_pelanggarans/1.json
  def update
    respond_to do |format|
      if @tabel_pelanggaran.update(tabel_pelanggaran_params)
        format.html { redirect_to tabel_pelanggaran_url(@tabel_pelanggaran), notice: "Tabel pelanggaran was successfully updated." }
        format.json { render :show, status: :ok, location: @tabel_pelanggaran }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tabel_pelanggaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabel_pelanggarans/1 or /tabel_pelanggarans/1.json
  def destroy
    @tabel_pelanggaran.destroy

    respond_to do |format|
      format.html { redirect_to tabel_pelanggarans_url, notice: "Tabel pelanggaran was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabel_pelanggaran
      @tabel_pelanggaran = TabelPelanggaran.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tabel_pelanggaran_params
      params.require(:tabel_pelanggaran).permit(:ID_Nota, :No_Nota, :Tgl_Pelanggaran, :Lokasi, :Pelanggaran, :Tindakan)
    end
end

hasbi/app/helpers/tabel_pelanggarans_helper.rb
module TabelPelanggaransHelper
end

hasbi/app/views/tabel_pelanggarans/_form.html.erb
<%= form_with(model: tabel_pelanggaran) do |form| %>
  <% if tabel_pelanggaran.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tabel_pelanggaran.errors.count, "error") %> prohibited this tabel_pelanggaran from being saved:</h2>

      <ul>
        <% tabel_pelanggaran.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ID_Nota, style: "display: block" %>
    <%= form.number_field :ID_Nota %>
  </div>

  <div>
    <%= form.label :No_Nota, style: "display: block" %>
    <%= form.text_field :No_Nota %>
  </div>

  <div>
    <%= form.label :Tgl_Pelanggaran, style: "display: block" %>
    <%= form.text_field :Tgl_Pelanggaran %>
  </div>

  <div>
    <%= form.label :Lokasi, style: "display: block" %>
    <%= form.text_field :Lokasi %>
  </div>

  <div>
    <%= form.label :Pelanggaran, style: "display: block" %>
    <%= form.text_field :Pelanggaran %>
  </div>

  <div>
    <%= form.label :Tindakan, style: "display: block" %>
    <%= form.text_field :Tindakan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hasbi/app/views/tabel_pelanggarans/_tabel_pelanggaran.html.erb
<div id="<%= dom_id tabel_pelanggaran %>">
  <p>
    <strong>Id nota:</strong>
    <%= tabel_pelanggaran.ID_Nota %>
  </p>

  <p>
    <strong>No nota:</strong>
    <%= tabel_pelanggaran.No_Nota %>
  </p>

  <p>
    <strong>Tgl pelanggaran:</strong>
    <%= tabel_pelanggaran.Tgl_Pelanggaran %>
  </p>

  <p>
    <strong>Lokasi:</strong>
    <%= tabel_pelanggaran.Lokasi %>
  </p>

  <p>
    <strong>Pelanggaran:</strong>
    <%= tabel_pelanggaran.Pelanggaran %>
  </p>

  <p>
    <strong>Tindakan:</strong>
    <%= tabel_pelanggaran.Tindakan %>
  </p>

</div>

hasbi/app/views/tabel_pelanggarans/edit.html.erb
<h1>Editing tabel pelanggaran</h1>

<%= render "form", tabel_pelanggaran: @tabel_pelanggaran %>

<br>

<div>
  <%= link_to "Show this tabel pelanggaran", @tabel_pelanggaran %> |
  <%= link_to "Back to tabel pelanggarans", tabel_pelanggarans_path %>
</div>

hasbi/app/views/tabel_pelanggarans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tabel pelanggarans</h1>

<div id="tabel_pelanggarans">
  <% @tabel_pelanggarans.each do |tabel_pelanggaran| %>
    <%= render tabel_pelanggaran %>
    <p>
      <%= link_to "Show this tabel pelanggaran", tabel_pelanggaran %>
    </p>
  <% end %>
</div>

<%= link_to "New tabel pelanggaran", new_tabel_pelanggaran_path %>

hasbi/app/views/tabel_pelanggarans/new.html.erb
<h1>New tabel pelanggaran</h1>

<%= render "form", tabel_pelanggaran: @tabel_pelanggaran %>

<br>

<div>
  <%= link_to "Back to tabel pelanggarans", tabel_pelanggarans_path %>
</div>

hasbi/app/views/tabel_pelanggarans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tabel_pelanggaran %>

<div>
  <%= link_to "Edit this tabel pelanggaran", edit_tabel_pelanggaran_path(@tabel_pelanggaran) %> |
  <%= link_to "Back to tabel pelanggarans", tabel_pelanggarans_path %>

  <%= button_to "Destroy this tabel pelanggaran", @tabel_pelanggaran, method: :delete %>
</div>