hasbi/config/routes.rb
Rails.application.routes.draw do
  resources :tabel_pelanggarans
  resources :tabel_area_spvs
  resources :tabel_kendaraans
  resources :tabel_sopirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

hasbi/app/controllers/tabel_sopirs_controller.rb
class TabelSopirsController < ApplicationController
  before_action :set_tabel_sopir, only: %i[ show edit update destroy ]

  # GET /tabel_sopirs or /tabel_sopirs.json
  def index
    @tabel_sopirs = TabelSopir.all
  end

  # GET /tabel_sopirs/1 or /tabel_sopirs/1.json
  def show
  end

  # GET /tabel_sopirs/new
  def new
    @tabel_sopir = TabelSopir.new
  end

  # GET /tabel_sopirs/1/edit
  def edit
  end

  # POST /tabel_sopirs or /tabel_sopirs.json
  def create
    @tabel_sopir = TabelSopir.new(tabel_sopir_params)

    respond_to do |format|
      if @tabel_sopir.save
        format.html { redirect_to tabel_sopir_url(@tabel_sopir), notice: "Tabel sopir was successfully created." }
        format.json { render :show, status: :created, location: @tabel_sopir }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tabel_sopir.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabel_sopirs/1 or /tabel_sopirs/1.json
  def update
    respond_to do |format|
      if @tabel_sopir.update(tabel_sopir_params)
        format.html { redirect_to tabel_sopir_url(@tabel_sopir), notice: "Tabel sopir was successfully updated." }
        format.json { render :show, status: :ok, location: @tabel_sopir }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tabel_sopir.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabel_sopirs/1 or /tabel_sopirs/1.json
  def destroy
    @tabel_sopir.destroy

    respond_to do |format|
      format.html { redirect_to tabel_sopirs_url, notice: "Tabel sopir was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabel_sopir
      @tabel_sopir = TabelSopir.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tabel_sopir_params
      params.require(:tabel_sopir).permit(:SIM, :namaSopir, :JK, :Kota, :Provinsi, :TglLhr, :TB, :BB)
    end
end

hasbi/app/helpers/tabel_sopirs_helper.rb
module TabelSopirsHelper
end

hasbi/app/views/tabel_sopirs/_form.html.erb
<%= form_with(model: tabel_sopir) do |form| %>
  <% if tabel_sopir.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tabel_sopir.errors.count, "error") %> prohibited this tabel_sopir from being saved:</h2>

      <ul>
        <% tabel_sopir.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :SIM, style: "display: block" %>
    <%= form.number_field :SIM %>
  </div>

  <div>
    <%= form.label :namaSopir, style: "display: block" %>
    <%= form.text_field :namaSopir %>
  </div>

  <div>
    <%= form.label :JK, style: "display: block" %>
    <%= form.text_field :JK %>
  </div>

  <div>
    <%= form.label :Kota, style: "display: block" %>
    <%= form.text_field :Kota %>
  </div>

  <div>
    <%= form.label :Provinsi, style: "display: block" %>
    <%= form.text_field :Provinsi %>
  </div>

  <div>
    <%= form.label :TglLhr, style: "display: block" %>
    <%= form.text_field :TglLhr %>
  </div>

  <div>
    <%= form.label :TB, style: "display: block" %>
    <%= form.text_field :TB %>
  </div>

  <div>
    <%= form.label :BB, style: "display: block" %>
    <%= form.number_field :BB %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hasbi/app/views/tabel_sopirs/_tabel_sopir.html.erb
<div id="<%= dom_id tabel_sopir %>">
  <p>
    <strong>Sim:</strong>
    <%= tabel_sopir.SIM %>
  </p>

  <p>
    <strong>Namasopir:</strong>
    <%= tabel_sopir.namaSopir %>
  </p>

  <p>
    <strong>Jk:</strong>
    <%= tabel_sopir.JK %>
  </p>

  <p>
    <strong>Kota:</strong>
    <%= tabel_sopir.Kota %>
  </p>

  <p>
    <strong>Provinsi:</strong>
    <%= tabel_sopir.Provinsi %>
  </p>

  <p>
    <strong>Tgllhr:</strong>
    <%= tabel_sopir.TglLhr %>
  </p>

  <p>
    <strong>Tb:</strong>
    <%= tabel_sopir.TB %>
  </p>

  <p>
    <strong>Bb:</strong>
    <%= tabel_sopir.BB %>
  </p>

</div>

hasbi/app/views/tabel_sopirs/edit.html.erb
<h1>Editing tabel sopir</h1>

<%= render "form", tabel_sopir: @tabel_sopir %>

<br>

<div>
  <%= link_to "Show this tabel sopir", @tabel_sopir %> |
  <%= link_to "Back to tabel sopirs", tabel_sopirs_path %>
</div>

hasbi/app/views/tabel_sopirs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tabel sopirs</h1>

<div id="tabel_sopirs">
  <% @tabel_sopirs.each do |tabel_sopir| %>
    <%= render tabel_sopir %>
    <p>
      <%= link_to "Show this tabel sopir", tabel_sopir %>
    </p>
  <% end %>
</div>

<%= link_to "New tabel sopir", new_tabel_sopir_path %>

hasbi/app/views/tabel_sopirs/new.html.erb
<h1>New tabel sopir</h1>

<%= render "form", tabel_sopir: @tabel_sopir %>

<br>

<div>
  <%= link_to "Back to tabel sopirs", tabel_sopirs_path %>
</div>

hasbi/app/views/tabel_sopirs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tabel_sopir %>

<div>
  <%= link_to "Edit this tabel sopir", edit_tabel_sopir_path(@tabel_sopir) %> |
  <%= link_to "Back to tabel sopirs", tabel_sopirs_path %>

  <%= button_to "Destroy this tabel sopir", @tabel_sopir, method: :delete %>
</div>