Akmal/config/routes.rb
Rails.application.routes.draw do
  resources :transaksis
  resources :barangs
  resources :pegawais
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Akmal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Akmal/app/models/barang.rb
class Barang < ApplicationRecord
    has_many :transaksi
end

Akmal/app/models/pegawai.rb
class Pegawai < ApplicationRecord
    has_many :transaksi
    enum :status, [:active, :not_active]
end

Akmal/app/models/transaksi.rb
class Transaksi < ApplicationRecord
    belongs_to :pegawai
    belongs_to :barang
    enum :payment, [:cash, :qris, :debit]
end

Akmal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Akmal/app/controllers/barangs_controller.rb
class BarangsController < ApplicationController
  before_action :set_barang, only: %i[ show edit update destroy ]

  # GET /barangs or /barangs.json
  def index
    @barangs = Barang.all
  end

  # GET /barangs/1 or /barangs/1.json
  def show
  end

  # GET /barangs/new
  def new
    @barang = Barang.new
  end

  # GET /barangs/1/edit
  def edit
  end

  # POST /barangs or /barangs.json
  def create
    @barang = Barang.new(barang_params)

    respond_to do |format|
      if @barang.save
        format.html { redirect_to barang_url(@barang), notice: "Barang was successfully created." }
        format.json { render :show, status: :created, location: @barang }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barangs/1 or /barangs/1.json
  def update
    respond_to do |format|
      if @barang.update(barang_params)
        format.html { redirect_to barang_url(@barang), notice: "Barang was successfully updated." }
        format.json { render :show, status: :ok, location: @barang }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barangs/1 or /barangs/1.json
  def destroy
    @barang.destroy

    respond_to do |format|
      format.html { redirect_to barangs_url, notice: "Barang was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barang
      @barang = Barang.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def barang_params
      params.require(:barang).permit(:name, :harga, :qty)
    end
end

Akmal/app/controllers/pegawais_controller.rb
class PegawaisController < ApplicationController
  before_action :set_pegawai, only: %i[ show edit update destroy ]

  # GET /pegawais or /pegawais.json
  def index
    @pegawais = Pegawai.all
  end

  # GET /pegawais/1 or /pegawais/1.json
  def show
  end

  # GET /pegawais/new
  def new
    @pegawai = Pegawai.new
  end

  # GET /pegawais/1/edit
  def edit
  end

  # POST /pegawais or /pegawais.json
  def create
    @pegawai = Pegawai.new(pegawai_params)

    respond_to do |format|
      if @pegawai.save
        format.html { redirect_to pegawai_url(@pegawai), notice: "Pegawai was successfully created." }
        format.json { render :show, status: :created, location: @pegawai }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pegawai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pegawais/1 or /pegawais/1.json
  def update
    respond_to do |format|
      if @pegawai.update(pegawai_params)
        format.html { redirect_to pegawai_url(@pegawai), notice: "Pegawai was successfully updated." }
        format.json { render :show, status: :ok, location: @pegawai }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pegawai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pegawais/1 or /pegawais/1.json
  def destroy
    @pegawai.destroy

    respond_to do |format|
      format.html { redirect_to pegawais_url, notice: "Pegawai was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pegawai
      @pegawai = Pegawai.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pegawai_params
      pp = params.require(:pegawai).permit(:name, :status)
      pp[:status] = params[:pegawai][:status].to_i
      return pp
    end
end

Akmal/app/controllers/transaksis_controller.rb
class TransaksisController < ApplicationController
  before_action :set_transaksi, only: %i[ show edit update destroy ]

  # GET /transaksis or /transaksis.json
  def index
    @transaksis = Transaksi.all
  end

  # GET /transaksis/1 or /transaksis/1.json
  def show
  end

  # GET /transaksis/new
  def new
    @transaksi = Transaksi.new
  end

  # GET /transaksis/1/edit
  def edit
  end

  # POST /transaksis or /transaksis.json
  def create
    @transaksi = Transaksi.new(transaksi_params)

    respond_to do |format|
      if @transaksi.save
        format.html { redirect_to transaksi_url(@transaksi), notice: "Transaksi was successfully created." }
        format.json { render :show, status: :created, location: @transaksi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaksi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaksis/1 or /transaksis/1.json
  def update
    respond_to do |format|
      if @transaksi.update(transaksi_params)
        format.html { redirect_to transaksi_url(@transaksi), notice: "Transaksi was successfully updated." }
        format.json { render :show, status: :ok, location: @transaksi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaksi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaksis/1 or /transaksis/1.json
  def destroy
    @transaksi.destroy

    respond_to do |format|
      format.html { redirect_to transaksis_url, notice: "Transaksi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaksi
      @transaksi = Transaksi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaksi_params
      tp = params.require(:transaksi).permit(:name, :payment, :price, :qty)
      tp[:payment] = params[:transaksi][:payment].to_i
      return tp
    end
end

Akmal/app/helpers/application_helper.rb
module ApplicationHelper
end

Akmal/app/helpers/barangs_helper.rb
module BarangsHelper
end

Akmal/app/helpers/pegawais_helper.rb
module PegawaisHelper
end

Akmal/app/helpers/transaksis_helper.rb
module TransaksisHelper
end

Akmal/app/views/barangs/_barang.html.erb
<div id="<%= dom_id barang %>">
  <p>
    <strong>Name:</strong>
    <%= barang.name %>
  </p>

  <p>
    <strong>Harga:</strong>
    <%= barang.harga %>
  </p>

  <p>
    <strong>Qty:</strong>
    <%= barang.qty %>
  </p>

</div>

Akmal/app/views/barangs/_form.html.erb
<%= form_with(model: barang) do |form| %>
  <% if barang.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(barang.errors.count, "error") %> prohibited this barang from being saved:</h2>

      <ul>
        <% barang.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :harga, style: "display: block" %>
    <%= form.text_field :harga %>
  </div>

  <div>
    <%= form.label :qty, style: "display: block" %>
    <%= form.number_field :qty %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Akmal/app/views/barangs/edit.html.erb
<h1>Editing barang</h1>

<%= render "form", barang: @barang %>

<br>

<div>
  <%= link_to "Show this barang", @barang %> |
  <%= link_to "Back to barangs", barangs_path %>
</div>

Akmal/app/views/barangs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Barangs</h1>

<div id="barangs">
  <% @barangs.each do |barang| %>
    <%= render barang %>
    <p>
      <%= link_to "Show this barang", barang %>
    </p>
  <% end %>
</div>

<%= link_to "New barang", new_barang_path %>

Akmal/app/views/barangs/new.html.erb
<h1>New barang</h1>

<%= render "form", barang: @barang %>

<br>

<div>
  <%= link_to "Back to barangs", barangs_path %>
</div>

Akmal/app/views/barangs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @barang %>

<div>
  <%= link_to "Edit this barang", edit_barang_path(@barang) %> |
  <%= link_to "Back to barangs", barangs_path %>

  <%= button_to "Destroy this barang", @barang, method: :delete %>
</div>

Akmal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectakmal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>