hasbi/config/routes.rb
Rails.application.routes.draw do
  resources :tabel_pelanggarans
  resources :tabel_area_spvs
  resources :tabel_kendaraans
  resources :tabel_sopirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

hasbi/app/controllers/tabel_kendaraans_controller.rb
class TabelKendaraansController < ApplicationController
  before_action :set_tabel_kendaraan, only: %i[ show edit update destroy ]

  # GET /tabel_kendaraans or /tabel_kendaraans.json
  def index
    @tabel_kendaraans = TabelKendaraan.all
  end

  # GET /tabel_kendaraans/1 or /tabel_kendaraans/1.json
  def show
  end

  # GET /tabel_kendaraans/new
  def new
    @tabel_kendaraan = TabelKendaraan.new
  end

  # GET /tabel_kendaraans/1/edit
  def edit
  end

  # POST /tabel_kendaraans or /tabel_kendaraans.json
  def create
    @tabel_kendaraan = TabelKendaraan.new(tabel_kendaraan_params)

    respond_to do |format|
      if @tabel_kendaraan.save
        format.html { redirect_to tabel_kendaraan_url(@tabel_kendaraan), notice: "Tabel kendaraan was successfully created." }
        format.json { render :show, status: :created, location: @tabel_kendaraan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tabel_kendaraan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabel_kendaraans/1 or /tabel_kendaraans/1.json
  def update
    respond_to do |format|
      if @tabel_kendaraan.update(tabel_kendaraan_params)
        format.html { redirect_to tabel_kendaraan_url(@tabel_kendaraan), notice: "Tabel kendaraan was successfully updated." }
        format.json { render :show, status: :ok, location: @tabel_kendaraan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tabel_kendaraan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabel_kendaraans/1 or /tabel_kendaraans/1.json
  def destroy
    @tabel_kendaraan.destroy

    respond_to do |format|
      format.html { redirect_to tabel_kendaraans_url, notice: "Tabel kendaraan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabel_kendaraan
      @tabel_kendaraan = TabelKendaraan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tabel_kendaraan_params
      params.require(:tabel_kendaraan).permit(:ID_Kendaraan, :No_Kndrn, :Warna, :No_Lambung)
    end
end

hasbi/app/helpers/tabel_kendaraans_helper.rb
module TabelKendaraansHelper
end

hasbi/app/views/tabel_kendaraans/_form.html.erb
<%= form_with(model: tabel_kendaraan) do |form| %>
  <% if tabel_kendaraan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tabel_kendaraan.errors.count, "error") %> prohibited this tabel_kendaraan from being saved:</h2>

      <ul>
        <% tabel_kendaraan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ID_Kendaraan, style: "display: block" %>
    <%= form.number_field :ID_Kendaraan %>
  </div>

  <div>
    <%= form.label :No_Kndrn, style: "display: block" %>
    <%= form.text_field :No_Kndrn %>
  </div>

  <div>
    <%= form.label :Warna, style: "display: block" %>
    <%= form.text_field :Warna %>
  </div>

  <div>
    <%= form.label :No_Lambung, style: "display: block" %>
    <%= form.text_field :No_Lambung %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

hasbi/app/views/tabel_kendaraans/_tabel_kendaraan.html.erb
<div id="<%= dom_id tabel_kendaraan %>">
  <p>
    <strong>Id kendaraan:</strong>
    <%= tabel_kendaraan.ID_Kendaraan %>
  </p>

  <p>
    <strong>No kndrn:</strong>
    <%= tabel_kendaraan.No_Kndrn %>
  </p>

  <p>
    <strong>Warna:</strong>
    <%= tabel_kendaraan.Warna %>
  </p>

  <p>
    <strong>No lambung:</strong>
    <%= tabel_kendaraan.No_Lambung %>
  </p>

</div>

hasbi/app/views/tabel_kendaraans/edit.html.erb
<h1>Editing tabel kendaraan</h1>

<%= render "form", tabel_kendaraan: @tabel_kendaraan %>

<br>

<div>
  <%= link_to "Show this tabel kendaraan", @tabel_kendaraan %> |
  <%= link_to "Back to tabel kendaraans", tabel_kendaraans_path %>
</div>

hasbi/app/views/tabel_kendaraans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tabel kendaraans</h1>

<div id="tabel_kendaraans">
  <% @tabel_kendaraans.each do |tabel_kendaraan| %>
    <%= render tabel_kendaraan %>
    <p>
      <%= link_to "Show this tabel kendaraan", tabel_kendaraan %>
    </p>
  <% end %>
</div>

<%= link_to "New tabel kendaraan", new_tabel_kendaraan_path %>

hasbi/app/views/tabel_kendaraans/new.html.erb
<h1>New tabel kendaraan</h1>

<%= render "form", tabel_kendaraan: @tabel_kendaraan %>

<br>

<div>
  <%= link_to "Back to tabel kendaraans", tabel_kendaraans_path %>
</div>

hasbi/app/views/tabel_kendaraans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tabel_kendaraan %>

<div>
  <%= link_to "Edit this tabel kendaraan", edit_tabel_kendaraan_path(@tabel_kendaraan) %> |
  <%= link_to "Back to tabel kendaraans", tabel_kendaraans_path %>

  <%= button_to "Destroy this tabel kendaraan", @tabel_kendaraan, method: :delete %>
</div>